### PR TITLE
Split buffer and region handling logic.

### PR DESCRIPTION
**Pull request by proofit404**

### CODE REVIEW

**Comment by JorisE** [comment]
Thanks for your PR. I think it makes the project cleaner and easier to read, but just to be sure, this is not addressing any issue/bug is it?

**Comment by proofit404** [comment]
Yes, it's just provide a separation of concerns.

**Comment by JorisE** [comment]
Awesome. I have made you a collaborator, so feel free to merge it.

**Comment by proofit404** [comment]
Great! Thanks!

**Pull request merged**
